//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lesson
    {
        public int les_id { get; set; }
        public Nullable<int> chap_id { get; set; }
        public string les_name { get; set; }
        public string les_file_path_video { get; set; }
    
        public virtual tbl_chapter tbl_chapter { get; set; }
    }
}
