//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_chapter()
        {
            this.tbl_lesson = new HashSet<tbl_lesson>();
        }
    
        public int sub_id { get; set; }
        public int tea_id { get; set; }
        public string chap_name { get; set; }
        public string chap_description { get; set; }
        public string chap_file_path_pdf { get; set; }
        public int chap_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lesson> tbl_lesson { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_teacher tbl_teacher { get; set; }
    }
}
