//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webasp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_homework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_homework()
        {
            this.tbl_homework_detail = new HashSet<tbl_homework_detail>();
        }
    
        public int hom_id { get; set; }
        public int sub_id { get; set; }
        public string tea_id { get; set; }
        public string hom_description { get; set; }
        public string hom_type { get; set; }
        public Nullable<System.DateTime> hom_deadline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_homework_detail> tbl_homework_detail { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_teacher tbl_teacher { get; set; }
    }
}
