//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webasp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_score
    {
        public int sub_id { get; set; }
        public string stu_id { get; set; }
        public string stu_name { get; set; }
        public double attandance { get; set; }
        public double homework { get; set; }
        public double assignment { get; set; }
        public double final_exam { get; set; }
    
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
    }
}
