//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_schdedule
    {
        public int sub_id { get; set; }
        public int class_id { get; set; }
        public int tea_id { get; set; }
        public Nullable<System.TimeSpan> sch_time { get; set; }
        public string sch_day { get; set; }
    
        public virtual tbl_class tbl_class { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_teacher tbl_teacher { get; set; }
    }
}
