//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lesson
    {
        public int sub_id { get; set; }
        public int tea_id { get; set; }
        public string les_name { get; set; }
        public string les_desc { get; set; }
        public string les_chapter { get; set; }
        public string les_file_path { get; set; }
    
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_teacher tbl_teacher { get; set; }
    }
}
