//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_teacher()
        {
            this.tbl_attandance = new HashSet<tbl_attandance>();
            this.tbl_lesson = new HashSet<tbl_lesson>();
            this.tbl_schdedule = new HashSet<tbl_schdedule>();
            this.tbl_score = new HashSet<tbl_score>();
        }
    
        public int tea_id { get; set; }
        public string tea_email { get; set; }
        public string tea_name { get; set; }
        public string tea_gender { get; set; }
        public System.DateTime tea_dob { get; set; }
        public string tea_pob { get; set; }
        public string tea_address { get; set; }
        public string tea_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_attandance> tbl_attandance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lesson> tbl_lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_schdedule> tbl_schdedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_score> tbl_score { get; set; }
    }
}
