//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attandance
    {
        public int sub_id { get; set; }
        public int stu_id { get; set; }
        public int tea_id { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public string att_type { get; set; }
        public string att_description { get; set; }
    
        public virtual tbl_student tbl_student { get; set; }
        public virtual tbl_subject tbl_subject { get; set; }
        public virtual tbl_teacher tbl_teacher { get; set; }
    }
}
